### ISSUE TITLE
"#EXTVLCOPT:"can't work normally in 0.4.5.0

### ISSUE THREAD

**Issue by VirgilClyne** [stari4ek/tvirl#24] opened 2020-03-28 17:29 UTC
For example : 
"#EXTVLCOPT:http-referrer=" and "#EXTVLCOPT:http-user-agent=" in m3u8 can't work in 0.4.5.0

And I can't use "#EXTVLCOPT:aspect-ratio=16:9" force the source aspect ratio in any version

Device: MiBox S
Android TV 9.0

**Comment by stari4ek** [comment] 2020-04-01 07:54
> And I can't use "#EXTVLCOPT:aspect-ratio=16:9" force the source aspect ratio in any version

this is expected behavior. forcing aspect-ratio works from settings only.

> "#EXTVLCOPT:http-referrer=" and "#EXTVLCOPT:http-user-agent=" in m3u8 can't work in 0.4.5.0

need to check.
There were changes related to `#EXTVLCOPT` (did not load tag from header)

**Comment by stari4ek** [comment] 2020-04-01 14:26
non-working `user-agent` should be fixed with build 1964 for 0.4.5.0.

BTW, `http-referrer` never worked for TVirl. Do you really need it?
Any other http headers?

**Comment by stari4ek** [comment] 2020-04-01 14:34
New feature requests for `http-referrer` and `aspect-ratio` were created.
Will close this issue since `User-Agent` issue is fixed

**Closed as completed by stari4ek** 2020-04-01 14:34 UTC
Labels: bug

**Comment by stari4ek** [comment] 2020-04-17 12:42
FYI, `#EXTVLCOPT:http-referrer` will be supported starting from 0.4.5.2

**Comment by SlazE888** [comment] 2020-07-13 15:26
Михаил, когда ждать атрибут aspect-ratio?

**Comment by stari4ek** [comment] 2020-07-13 20:13
> Михаил, когда ждать атрибут aspect-ratio?

Думаю каналы 4:3 умрут быстрее.
Конкретных планов нет и есть много более приоритетных задач
